---

- name: update netbox directories
  file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - env

- name: update environment files
  template:
    src: "env/{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/env/{{ item }}"
  loop:
    - netbox.env
    - postgres.env
    - redis-cache.env
    - redis.env
  notify: restart netbox

- name: update configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/{{ item }}"
  loop:
    - docker-compose.yml
    - Caddyfile.yml
  notify: restart netbox

- name: remove outdated files
  file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: absent
  loop:
    - netbox.env
    - configuration/configuration.py
    - configuration/gunicorn_config.py
